---

- name: Add repository to install last Apache version
  apt_repository:
    repo: "{{ apache_repository }}"
    update_cache: true
  when: apache_repository

- name: Install packages.
  apt:
    update_cache: true
    cache_valid_time: 3600
    pkg: "{{ apache_install }}"
    state: present
  when: apache_install
